name: plant_z
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  animated_notch_bottom_bar: ^1.0.1
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_database: ^10.4.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # - ./assets/images/image.jpg
    # - ./assets/images/image2.jpg
    # - ./assets/images/f0.jpg
    # - ./assets/images/f1.jpg
    # - ./assets/images/f2.jpg   
    - ./assets/images/flower/
    - ./assets/images/image3.jpg
    - ./assets/data/flower.json
    - ./assets/data/plant.json
    # - ./assets/images/insta.png
    # - ./assets/images/youtube.png