// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHYogf03L0y5InYnKn6fMG9QMTsOwTsek',
    appId: '1:596959777198:web:23374ec5ccad84027d783f',
    messagingSenderId: '596959777198',
    projectId: 'plant-76d02',
    authDomain: 'plant-76d02.firebaseapp.com',
    storageBucket: 'plant-76d02.appspot.com',
    databaseURL: 'https://plant-76d02-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYzSF11drIcQofHUVxk24J8PIZ1II-_2c',
    appId: '1:596959777198:android:b1da79b1170cc60b7d783f',
    messagingSenderId: '596959777198',
    projectId: 'plant-76d02',
    storageBucket: 'plant-76d02.appspot.com',
    databaseURL: 'https://plant-76d02-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCetfmiTTksyMK2o-urIEBlqg_5lYH5tas',
    appId: '1:596959777198:ios:92f891d5bfc86ec07d783f',
    messagingSenderId: '596959777198',
    projectId: 'plant-76d02',
    storageBucket: 'plant-76d02.appspot.com',
    iosBundleId: 'com.example.plantz',
    databaseURL: 'https://plant-76d02-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCetfmiTTksyMK2o-urIEBlqg_5lYH5tas',
    appId: '1:596959777198:ios:6c213eac574f16497d783f',
    messagingSenderId: '596959777198',
    projectId: 'plant-76d02',
    storageBucket: 'plant-76d02.appspot.com',
    iosBundleId: 'com.example.plantz.RunnerTests',
  );
}
